/**
 * Code generation for Web Components
 */

export type AttrType = 'string' | 'int' | 'float' | 'bool';

export interface AttrConfig {
  name: string;
  type: AttrType;
  default?: string | number | boolean;
  reflect?: boolean;
}

export interface ComponentConfig {
  tag: string;
  module: string;
  attributes: AttrConfig[];
  shadow?: 'open' | 'closed' | 'none';
  styles?: string;
  output?: string;
}

/**
 * Generate Web Component JavaScript code
 */
export function generateComponentJS(config: ComponentConfig): string {
  const { tag, module, attributes, shadow = 'open', styles } = config;

  const className = tagToClassName(tag);
  const hasStyles = styles && styles.length > 0 && shadow !== 'none';

  const lines: string[] = [];

  // Header
  lines.push('// Generated by @mizchi/stella');
  lines.push("import { Signal, effect } from '@mizchi/luna-wcr';");
  lines.push(`import * as mod from '${module}';`);
  lines.push('');

  // Stylesheet
  if (hasStyles) {
    lines.push('const sheet = new CSSStyleSheet();');
    lines.push(`sheet.replaceSync(\`${escapeTemplate(styles)}\`);`);
    lines.push('');
  }

  // Class definition
  lines.push(`class ${className} extends HTMLElement {`);

  // observedAttributes
  const attrNames = attributes.map((a) => `'${a.name}'`).join(', ');
  lines.push(`  static observedAttributes = [${attrNames}];`);
  lines.push('');

  // Private fields - props
  lines.push('  #props = {');
  for (const attr of attributes) {
    const key = toCamelCase(attr.name);
    const defaultVal = attrDefaultToJS(attr);
    lines.push(`    ${key}: new Signal(${defaultVal}),`);
  }
  lines.push('  };');
  lines.push('  #dispose = null;');
  lines.push('  #connected = false;');
  lines.push('');

  // connectedCallback
  lines.push('  connectedCallback() {');
  lines.push('    this.#connected = true;');
  lines.push('    this.#syncAttributes();');
  lines.push('');

  // Shadow DOM setup
  if (shadow === 'none') {
    lines.push('    const shadow = this;');
    lines.push('    const isSSR = false;');
  } else {
    lines.push('    const isSSR = !!this.shadowRoot;');
    lines.push(`    const shadow = this.shadowRoot ?? this.attachShadow({ mode: '${shadow}' });`);
    if (hasStyles) {
      lines.push('    shadow.adoptedStyleSheets = [sheet];');
    }
  }
  lines.push('');

  // Template rendering (only for non-SSR)
  lines.push('    if (!isSSR && mod.template) {');
  lines.push('      shadow.innerHTML = mod.template(this.#getSnapshot());');
  lines.push('    }');
  lines.push('');

  // Create context with helper methods
  lines.push('    const ctx = {');
  lines.push('      element: this,');
  lines.push('      shadow,');
  lines.push('      props: this.#props,');
  lines.push('');
  lines.push('      bind: (selector, getter) => {');
  lines.push('        const el = shadow.querySelector(selector);');
  lines.push('        if (!el) return () => {};');
  lines.push('        return effect(() => { el.textContent = getter(); });');
  lines.push('      },');
  lines.push('');
  lines.push('      bindAttr: (selector, attr, signal) => {');
  lines.push('        const el = shadow.querySelector(selector);');
  lines.push('        if (!el) return () => {};');
  lines.push('        return signal.subscribe(() => {');
  lines.push('          const val = signal.get();');
  lines.push("          if (typeof val === 'boolean') {");
  lines.push("            val ? el.setAttribute(attr, '') : el.removeAttribute(attr);");
  lines.push('          } else {');
  lines.push('            el.setAttribute(attr, String(val));');
  lines.push('          }');
  lines.push('        });');
  lines.push('      },');
  lines.push('');
  lines.push('      on: (selector, event, handler) => {');
  lines.push('        const el = shadow.querySelector(selector);');
  lines.push('        if (!el) return () => {};');
  lines.push('        el.addEventListener(event, handler);');
  lines.push('        return () => el.removeEventListener(event, handler);');
  lines.push('      },');
  lines.push('    };');
  lines.push('');
  lines.push('    this.#dispose = mod.setup(ctx);');
  lines.push('  }');
  lines.push('');

  // disconnectedCallback
  lines.push('  disconnectedCallback() {');
  lines.push('    this.#connected = false;');
  lines.push('    this.#dispose?.();');
  lines.push('    this.#dispose = null;');
  lines.push('  }');
  lines.push('');

  // attributeChangedCallback
  lines.push('  attributeChangedCallback(name, _, newVal) {');
  lines.push('    if (!this.#connected) return;');
  lines.push('    switch (name) {');
  for (const attr of attributes) {
    const key = toCamelCase(attr.name);
    const parseExpr = attrParseExpr(attr);
    lines.push(`      case '${attr.name}':`);
    lines.push(`        this.#props.${key}.set(${parseExpr});`);
    lines.push('        break;');
  }
  lines.push('    }');
  lines.push('  }');
  lines.push('');

  // #syncAttributes
  lines.push('  #syncAttributes() {');
  for (const attr of attributes) {
    const key = toCamelCase(attr.name);
    const syncExpr = attrSyncExpr(attr);
    lines.push(`    this.#props.${key}.set(${syncExpr});`);
  }
  lines.push('  }');
  lines.push('');

  // #getSnapshot
  lines.push('  #getSnapshot() {');
  lines.push('    return {');
  for (const attr of attributes) {
    const key = toCamelCase(attr.name);
    lines.push(`      ${key}: this.#props.${key}.get(),`);
  }
  lines.push('    };');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Register
  lines.push(`customElements.define('${tag}', ${className});`);
  lines.push('');

  return lines.join('\n');
}

// Helper functions

function tagToClassName(tag: string): string {
  return tag
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toCamelCase(name: string): string {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function attrDefaultToJS(attr: AttrConfig): string {
  const def = attr.default;
  switch (attr.type) {
    case 'string':
      return `'${escapeString(String(def ?? ''))}'`;
    case 'int':
    case 'float':
      return String(def ?? 0);
    case 'bool':
      return def ? 'true' : 'false';
  }
}

function attrParseExpr(attr: AttrConfig): string {
  switch (attr.type) {
    case 'string':
      return "newVal ?? ''";
    case 'int':
      return `parseInt(newVal ?? '${attr.default ?? 0}', 10)`;
    case 'float':
      return `parseFloat(newVal ?? '${attr.default ?? 0}')`;
    case 'bool':
      return 'newVal !== null';
  }
}

function attrSyncExpr(attr: AttrConfig): string {
  switch (attr.type) {
    case 'string':
      return `this.getAttribute('${attr.name}') ?? '${escapeString(String(attr.default ?? ''))}'`;
    case 'int':
      return `parseInt(this.getAttribute('${attr.name}') ?? '${attr.default ?? 0}', 10)`;
    case 'float':
      return `parseFloat(this.getAttribute('${attr.name}') ?? '${attr.default ?? 0}')`;
    case 'bool':
      return `this.hasAttribute('${attr.name}')`;
  }
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function escapeTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}
