packages:
  - "astra"
  - "astra/examples/sol_landing"
  - "sol"
  - "js/*"
  - "js/luna/examples"
  - "js/luna/examples_preact"

linkWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
