// @ts-nocheck
// Direct low-level re-exports from MoonBit JS API

export {
  // Signals
  createSignal,
  get,
  set,
  update,
  peek,
  subscribe,
  map,
  createMemo,
  combine,
  effect,
  renderEffect,
  batchStart,
  batchEnd,
  runUntracked,
  batch,
  onCleanup,
  createRoot,
  getOwner,
  runWithOwner,
  hasOwner,
  onMount,
  // DOM
  text,
  textDyn,
  render,
  mount,
  show,
  jsx,
  jsxs,
  Fragment,
  createElement,
  createElementNs,
  svgNs,
  mathmlNs,
  events,
  forEach,
  // Utilities
  debounced,
  // Router
  routePage,
  routePageTitled,
  routePageFull,
  createRouter,
  routerNavigate,
  routerReplace,
  routerGetPath,
  routerGetMatch,
  routerGetBase,
  // Context
  createContext,
  provide,
  useContext,
  // Resource
  createResource,
  createDeferred,
  resourceGet,
  resourcePeek,
  resourceRefetch,
  resourceIsPending,
  resourceIsSuccess,
  resourceIsFailure,
  resourceValue,
  resourceError,
  stateIsPending,
  stateIsSuccess,
  stateIsFailure,
  stateValue,
  stateError,
  // Portal
  portalToBody,
  portalToSelector,
  portalWithShadow,
  portalToElementWithShadow,
} from "../../../_build/js/release/build/js/api/api.js";
