// Generated by scripts/generate-css-pseudos.mjs; do not edit.
export const pseudoNames = Object.freeze({
  "Active": {
    "selector": ":active",
    "functional": false
  },
  "After": {
    "selector": "::after",
    "functional": false
  },
  "AnyLink": {
    "selector": ":any-link",
    "functional": false
  },
  "Autofill": {
    "selector": ":autofill",
    "functional": false
  },
  "Backdrop": {
    "selector": "::backdrop",
    "functional": false
  },
  "Before": {
    "selector": "::before",
    "functional": false
  },
  "Checked": {
    "selector": ":checked",
    "functional": false
  },
  "Default": {
    "selector": ":default",
    "functional": false
  },
  "Defined": {
    "selector": ":defined",
    "functional": false
  },
  "Dir": {
    "selector": ":dir",
    "functional": true
  },
  "Disabled": {
    "selector": ":disabled",
    "functional": false
  },
  "Empty": {
    "selector": ":empty",
    "functional": false
  },
  "Enabled": {
    "selector": ":enabled",
    "functional": false
  },
  "FileSelectorButton": {
    "selector": "::file-selector-button",
    "functional": false
  },
  "FirstChild": {
    "selector": ":first-child",
    "functional": false
  },
  "FirstLetter": {
    "selector": "::first-letter",
    "functional": false
  },
  "FirstLine": {
    "selector": "::first-line",
    "functional": false
  },
  "FirstOfType": {
    "selector": ":first-of-type",
    "functional": false
  },
  "Focus": {
    "selector": ":focus",
    "functional": false
  },
  "FocusVisible": {
    "selector": ":focus-visible",
    "functional": false
  },
  "FocusWithin": {
    "selector": ":focus-within",
    "functional": false
  },
  "Fullscreen": {
    "selector": ":fullscreen",
    "functional": false
  },
  "Has": {
    "selector": ":has",
    "functional": true
  },
  "Highlight": {
    "selector": "::highlight",
    "functional": true
  },
  "Hover": {
    "selector": ":hover",
    "functional": false
  },
  "InRange": {
    "selector": ":in-range",
    "functional": false
  },
  "Indeterminate": {
    "selector": ":indeterminate",
    "functional": false
  },
  "Invalid": {
    "selector": ":invalid",
    "functional": false
  },
  "Is": {
    "selector": ":is",
    "functional": true
  },
  "Lang": {
    "selector": ":lang",
    "functional": true
  },
  "LastChild": {
    "selector": ":last-child",
    "functional": false
  },
  "LastOfType": {
    "selector": ":last-of-type",
    "functional": false
  },
  "Link": {
    "selector": ":link",
    "functional": false
  },
  "Marker": {
    "selector": "::marker",
    "functional": false
  },
  "Modal": {
    "selector": ":modal",
    "functional": false
  },
  "Not": {
    "selector": ":not",
    "functional": true
  },
  "NthChild": {
    "selector": ":nth-child",
    "functional": true
  },
  "NthLastChild": {
    "selector": ":nth-last-child",
    "functional": true
  },
  "NthLastOfType": {
    "selector": ":nth-last-of-type",
    "functional": true
  },
  "NthOfType": {
    "selector": ":nth-of-type",
    "functional": true
  },
  "OnlyChild": {
    "selector": ":only-child",
    "functional": false
  },
  "OnlyOfType": {
    "selector": ":only-of-type",
    "functional": false
  },
  "Open": {
    "selector": ":open",
    "functional": false
  },
  "Optional": {
    "selector": ":optional",
    "functional": false
  },
  "OutOfRange": {
    "selector": ":out-of-range",
    "functional": false
  },
  "Part": {
    "selector": "::part",
    "functional": true
  },
  "PictureInPicture": {
    "selector": ":picture-in-picture",
    "functional": false
  },
  "Placeholder": {
    "selector": "::placeholder",
    "functional": false
  },
  "PlaceholderShown": {
    "selector": ":placeholder-shown",
    "functional": false
  },
  "PopoverOpen": {
    "selector": ":popover-open",
    "functional": false
  },
  "ReadOnly": {
    "selector": ":read-only",
    "functional": false
  },
  "ReadWrite": {
    "selector": ":read-write",
    "functional": false
  },
  "Required": {
    "selector": ":required",
    "functional": false
  },
  "Root": {
    "selector": ":root",
    "functional": false
  },
  "Scope": {
    "selector": ":scope",
    "functional": false
  },
  "Selection": {
    "selector": "::selection",
    "functional": false
  },
  "Slotted": {
    "selector": "::slotted",
    "functional": true
  },
  "State": {
    "selector": ":state",
    "functional": true
  },
  "Target": {
    "selector": ":target",
    "functional": false
  },
  "UserInvalid": {
    "selector": ":user-invalid",
    "functional": false
  },
  "UserValid": {
    "selector": ":user-valid",
    "functional": false
  },
  "Valid": {
    "selector": ":valid",
    "functional": false
  },
  "Visited": {
    "selector": ":visited",
    "functional": false
  },
  "Where": {
    "selector": ":where",
    "functional": true
  }
});
