// Bundle only our compiler and Node built-ins into MoonBit's JS FFI. The resulting
// Mooncake has no dependency on this repository's layout or on an npm compiler.
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const result = await build({
  absWorkingDir: root,
  entryPoints: ["js/luna/src/css/moon-cli.ts"],
  bundle: true,
  platform: "node",
  format: "iife",
  target: "node24",
  write: false,
  legalComments: "none",
});
const js = result.outputFiles[0].text.trimEnd();
const source = `// Generated by scripts/generate-css-cli.mjs; do not edit.
// This bundles the same static compiler used by the npm/Vite integration.

///|
extern "js" fn run_cli() -> Unit =
  #| () => {
  #|   import("node:module").then(({ createRequire }) => {
  #|     const require = createRequire(process.cwd() + "/__luna_css_cli__.cjs");
${js.split("\n").map(line => "  #|" + line).join("\n")}
  #|   }).catch(error => {
  #|     console.error(error);
  #|     process.exitCode = 1;
  #|   });
  #| }
`;
const output = new URL("../luna/src/cmd/css/cli_generated.mbt", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8") !== source) throw new Error("CSS CLI bundle is stale; run just generate-css-cli");
} else writeFileSync(output, source);
console.log(`${process.argv.includes("--check") ? "Checked" : "Generated"} self-contained MoonBit CSS CLI`);
